services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nginx-test-task
    ports:
    - 9999:80
    - 5555:443
    volumes: 
    - ./html:/usr/share/nginx/html
    restart: always